apiVersion: keda.sh/v1alpha1
kind: TriggerAuthentication
metadata:
  name: trigger-auth-service-bus-orders
spec:
  secretTargetRef:
  - parameter: connection
    name: secrets-order-management
    key: servicebus-order-management-connectionstring
---
apiVersion: v1
kind: Secret
metadata:
  name: secrets-order-management
  labels:
    app: order-processor
data:
  servicebus-order-management-connectionstring: RW5kcG9pbnQ9c2I6Ly9rZWRhc2Iuc2VydmljZWJ1cy53aW5kb3dzLm5ldC87U2hhcmVkQWNjZXNzS2V5TmFtZT1rZWRhLW1vbml0b3I7U2hhcmVkQWNjZXNzS2V5PVdLcXJoUWhhRHYwQnZJUTBpaEJXeDFWamRjSXJjeWdTNlVTKzZWYUZRT1E9O0VudGl0eVBhdGg9b3JkZXJzCg==
---
apiVersion: keda.sh/v1alpha1 
kind: ScaledObject
metadata:
  name: order-processor-scaler
spec:
  scaleTargetRef:
    name: order-processor
  minReplicaCount: 1 #Change to define how many minimum replicas you want
  maxReplicaCount: 10
  triggers:
  - type: azure-servicebus
    metadata:
      queueName: orders
      messageCount: '5'
    authenticationRef:
      name: trigger-auth-service-bus-orders